tasks:
  - init: npm install
    command: >
             npm start & 
             sleep 10 &&
             GIT_SSL_NO_VERIFY=true git -c "http.proxy=http://127.0.0.1:8080" clone https://github.com/gerardo-junior/private.git .tmp/github &
             GIT_SSL_NO_VERIFY=true git -c "http.proxy=http://127.0.0.1:8080" clone https://gitlab.com/gerardo-junior/private.git .tmp/gitlab &
